name: cpp ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: |
        cmake -B build
        cmake --build build
        ctest --test-dir build --rerun-failed --output-on-failure